#!/bin/sh
source ~/dotfiles/antigen/antigen.zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions

antigen bundle docker
antigen bundle redis-cli

antigen apply
